### ISSUE TITLE
Consolidation of chagrade

### ISSUE THREAD

**Issue by madclam** [codalab/chagrade#58]
This recaps what needs to be done to implement Magali's class.

- [ ] P1 BUG **CSV student enrollment:** Enrolling multiple students is not working.  https://github.com/codalab/chagrade/issues/56
- [ ] P1 FEATURE **View logs on chagrade:** When submissions fail for students, they do not know. Codalab should send back that information to Chagrade the status of the submission when it finishes or fails. Would be useful to link student to chagrade bot logs for their submissions.
- [ ] P1 BUG **Choose date is obfuscated** https://github.com/codalab/chagrade/issues/59
- [ ] P1 FEATURE **Text wrapping** : no text wrapping in the boxes
- [ ] P1 BUG **Grades in class list (student view)** Student class list doesn't show grades. Last two columns of table are empty. https://chagrade.lri.fr/profiles/student_overview/

- [ ] P2 FEATURE **Submission limit:** Chagrade bot gets rate limited when a bunch of students are submitting. Limit them on Chagrade end and remove limits on Chagrade Bot on Codalab. https://github.com/codalab/chagrade/issues/57
- [ ] P2 FEATURE **We should be able to submit directly a zip file without github interface.**
       - Upload zip file directly
       - Upload url of zip file from arbitrary domain
       - Give instructor the option of forcing Github usage
- [ ] P2 FEATURE **Automatically enroll instructor** in his or her own class as a student
- [ ] P2 FEATURE **Split metrics** It would be nice to split the metrics between 'challenge submissions' (several submissions) and homework with no competition (usually only one submission)
- [ ] P2 FEATURE **Class number** The class 'number' has to be unique, which might be an issue in the future. Consider the uniqueness of class numbers, because multiple Universities may have the same class number. e.g. PSYC 101

- [ ] P3 FEATURE **Add challenge link on homework page:** Consider placing Codalab challenge button on the submit homework page as well.
- [ ] P3 FEATURE **Grades in chart** On metrics, put grade in charts, rather than only competition score. Then give the option to show questions_only homework and competition homework.
- [ ] P3 FEATURE **Activate Class** in wizard does not have functionality for "Test your class" or "Download your bundle" (Ask Tyler about this). "Test your class" could just be a link to the student view if automatic enrollment works.
- [ ] P3 FEATURE **Open syllabus in new window**
- [ ] P3 BUG **Cancel student creation** When I open the window to add a student to my class (https://chagrade.lri.fr/klasses/wizard/4/enroll), the "cancel" button doesn't work. But, if I reload the page, then I directly come back to my class. I use Firefox 68.2.0esr

TODO: Isabelle and Alexis:
?? reproduce error in grading https://github.com/codalab/chagrade/issues/54
?? Reproduce BUG **Class score** Overall metrics is not properly calculating averaged class score when only one student has submitted one time. One of the homeworks is questions only. 
                    e.g. Klass_pk=2 on chagrade.lri.fr
?? Verify download CSVs
?? Add information to Wiki: https://github.com/codalab/chagrade/issues/30

Wish list:
- [ ] Editable profiles.
- [ ] There is no notion of multiple instructors for the same class.
- [ ] Informative error messages.
- [ ] Class templates (to be able to clone classes)
- [ ] Jupyter Notebook Integration
- [ ] Fractional grades are not allowed. Error message is obscure when fractional grades are given
- [ ] When max submission per day is exceeded, score is 0 (instead of last score)
